# Generated by Django 4.0.5 on 2023-04-09 15:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='İsim')),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Yazar')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim : (535x595)')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='İsim')),
                ('slug', models.SlugField(max_length=200)),
                ('list', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (500x500)')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (1500x1000)')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Başlık')),
                ('info', ckeditor_uploader.fields.RichTextUploadingField()),
                ('m2', models.CharField(db_index=True, max_length=200, verbose_name='Room')),
                ('person', models.CharField(db_index=True, max_length=200, verbose_name='Person')),
                ('minibar', models.CharField(db_index=True, max_length=200, verbose_name='Bar')),
                ('wifi', models.CharField(db_index=True, max_length=200, verbose_name='Wifi')),
                ('heatwater', models.CharField(db_index=True, max_length=200, verbose_name='Heat Water')),
                ('aircon', models.CharField(db_index=True, max_length=200, verbose_name='Aircon')),
                ('shower', models.CharField(db_index=True, max_length=200, verbose_name='Shower')),
                ('tv', models.CharField(db_index=True, max_length=200, verbose_name='Tv')),
                ('des', models.CharField(default='SEO Description', max_length=500)),
                ('key', models.CharField(default='SEO Keyword için Giriş', max_length=550)),
                ('available', models.BooleanField(default=True)),
                ('facebook', models.CharField(default='Facebook Adresini Giriniz', max_length=500)),
                ('instagram', models.CharField(default='İnstagram Adresini Giriniz', max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seastar.category', verbose_name='Kategori')),
            ],
        ),
    ]
