# Generated by Django 4.0.5 on 2023-04-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Marka İsmi', max_length=150, verbose_name='Müşteri İsmi')),
                ('info', models.TextField(max_length=250, verbose_name='Müşteri Yorumu')),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, max_length=200, verbose_name='No')),
                ('list', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (350x324)')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (1920x1080)')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, max_length=200, verbose_name='No')),
                ('list', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (350x324)')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (1920x1080)')),
            ],
        ),
    ]
