# Generated by Django 4.0.5 on 2023-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0002_comment_pool_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(db_index=True, max_length=200, verbose_name='No')),
                ('list', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (350x324)')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d', verbose_name='Resim: (1920x1080)')),
            ],
        ),
        migrations.AddField(
            model_name='welcome',
            name='title',
            field=models.CharField(default=21, max_length=500, verbose_name='Başlık'),
            preserve_default=False,
        ),
    ]
