# Generated by Django 4.0.5 on 2023-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0003_gallery_welcome_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(db_index=True, default=21, max_length=200, verbose_name='Fiyat'),
            preserve_default=False,
        ),
    ]
