# Generated by Django 4.0.5 on 2023-04-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0009_product_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='welcome',
            field=models.CharField(db_index=True, max_length=10000, verbose_name='İlk Sayfa Açıklaması'),
        ),
    ]
