# Generated by Django 4.0.5 on 2023-04-17 18:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seastar', '0010_alter_product_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
